_BASE_: continual_maskformer2_R101_bs8_160k.yaml
CONT:
  TOT_CLS: 150
  BASE_CLS: 100
  INC_CLS: 50
  TASK: 1
  LIB_SIZE: 80
  VQ_NUMBER: 1
  FREEZE_LABEL: False
  DISTRIBUTION_ALPHA: 0.25
  PSD_LABEL_THRESHOLD: 0.0
  PSD_OVERLAP_THRESHOLD : 0.8
  KL_WEIGHT : 2.0
  KL_ALL : True
  KD_DECODER : False
  KD_TEMPERATURE: 1.0
  KD_TEMPERATURE2: 2.0
SOLVER:
  STEPS: (42500, 47500)
MODEL:
  MASK_FORMER:
    TEST:
      OBJECT_MASK_THRESHOLD: 0.8
OUTPUT_DIR: ./output/ss/100-50/step1
