_BASE_: continual_maskformer2_R101_bs8_160k.yaml
CONT:
  TOT_CLS: 150
  BASE_CLS: 100
  INC_CLS: 5
  TASK: 1
  LIB_SIZE: 80
  PSD_LABEL_THRESHOLD: 0.0
  PSD_OVERLAP_THRESHOLD : 0.8
  VQ_NUMBER: 3
  FREEZE_LABEL: False
  KL_WEIGHT : 2.0
  KL_ALL : True
  KD_DECODER : True
  KD_TEMPERATURE : 1.0
  KD_TEMPERATURE2 : 2.0
  FILTER_KD : False
SOLVER:
  STEPS: (4250, 4750)
MODEL:
  MASK_FORMER:
    TEST:
      OBJECT_MASK_THRESHOLD: 0.8
OUTPUT_DIR: ./output/ss/100-5/step1