_BASE_: continual_maskformer2_R50_bs8_160k.yaml
CONT:
  TOT_CLS: 150
  BASE_CLS: 100
  INC_CLS: 50
  TASK: 1
  VQ_NUMBER: 0
  DISTRIBUTION_ALPHA: 0.25
  LIB_SIZE: 80
  PSD_LABEL_THRESHOLD: 0.35
  FREEZE_LABEL: False
  KL_WEIGHT : 2.0
  KL_ALL : True
  KD_TEMPERATURE : 1.0
  KD_TEMPERATURE2 : 1.0
  KD_DECODER : False
TEST:
  EVAL_PERIOD: 10000
SOLVER:
  STEPS: (40000, 45000)
MODEL:
  MASK_FORMER:
    TEST:
      OBJECT_MASK_THRESHOLD: 0.2
OUTPUT_DIR: ./output/ps/100-50/step1